# Generated by Django 5.0.14 on 2026-09-21 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('values', 'Values'), ('money', 'Money'), ('relationships', 'Relationships'), ('risk', 'Risk'), ('creativity', 'Creativity'), ('goals', 'Goals'), ('habits', 'Habits')], max_length=32)),
                ('text', models.TextField()),
                ('is_onboarding', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
